name: Build and publish to NPM

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ startsWith(github.event.head_commit.message, 'release') }}

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - name: Ensure npm is at latest version
              run: npm install -g npm

            - name: Clean install dependencies
              run: npm ci

            - name: Bundle web version
              run: |
                  npm run build:web

            - name: Commit changes
              continue-on-error: true
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add ./web
                  git commit -m "build: build web lib version"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    publish:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - name: Ensure npm is at latest version
              run: npm install -g npm

            - name: Clean install dependencies
              run: npm ci

            - name: Publish to npm
              run: |
                  npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
